-- use plugins
require 'plugins'
--
-- plugins configuration
require 'config.catppuccin'
require 'config.packer'
require 'config.neodev' -- should be before lsp-zero!
require 'config.lsp-zero'
require 'config.hlslens'
require 'config.indents'
require 'config.line-numbers'
require 'config.neotree'
require 'config.clipboard'
require 'config.treesitter'
require 'config.telescope'
require 'config.galaxyline'
require 'config.windows'
require 'config.openscad'
require 'config.treesitter-textobjects'
require 'config.trouble'
require 'config.lsp-signature'
require 'config.nvim-dap' -- should be after lsp zero!
require 'config.neotest'
require 'config.personal'
require 'config.which-key'
require 'config.comment'
require 'config.nvim-surround'
require 'config.dim'
require 'config.nvim-lightbulb'
require 'config.leap'
require 'config.dap-ui'
require 'config.highlights'
require 'config.pretty-fold'
require 'config.rest'
require 'config.telekasten'

-- remaps
require 'remaps.leader'
require 'remaps.neotree'
require 'remaps.hlslens'
require 'remaps.telescope'
require 'remaps.trouble'
require 'remaps.undotree'
require 'remaps.windows'
require 'remaps.lazygit'
require 'remaps.openscad'
require 'remaps.whichkey'
require 'remaps.harpoon'
require 'remaps.nvim-dap'
require 'remaps.move'
require 'remaps.nvim-blame-line'
require 'remaps.personal'
require 'remaps.neotest'
require 'remaps.vim-easy-align'
require 'remaps.nvim-code-action-menu'
require 'remaps.rest'
require 'remaps.telekasten'
--
